require('core.plugin_config.leap')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.comment')
require('core.plugin_config.lspconfig')
require('core.plugin_config.mini-surround')
require('core.plugin_config.treesitter')
require('core.plugin_config.indent_blankline')
require('core.plugin_config.cmp')

require('mini.bracketed').setup()
require('bufferline').setup()
require('lualine').setup()
require('mason').setup()
require('mason-lspconfig').setup()
